// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Node sends his ID at first contact
type NodeInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeInfo) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type NodesList struct {
	Nodes                []*NodeInfo `protobuf:"bytes,1,rep,name=Nodes,json=nodes,proto3" json:"Nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NodesList) Reset()         { *m = NodesList{} }
func (m *NodesList) String() string { return proto.CompactTextString(m) }
func (*NodesList) ProtoMessage()    {}
func (*NodesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *NodesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodesList.Unmarshal(m, b)
}
func (m *NodesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodesList.Marshal(b, m, deterministic)
}
func (m *NodesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodesList.Merge(m, src)
}
func (m *NodesList) XXX_Size() int {
	return xxx_messageInfo_NodesList.Size(m)
}
func (m *NodesList) XXX_DiscardUnknown() {
	xxx_messageInfo_NodesList.DiscardUnknown(m)
}

var xxx_messageInfo_NodesList proto.InternalMessageInfo

func (m *NodesList) GetNodes() []*NodeInfo {
	if m != nil {
		return m.Nodes
	}
	return nil
}

//Timeout is the time interval for checking the connection with the Node
type Timeout struct {
	Timeout              int64    `protobuf:"varint,1,opt,name=Timeout,json=timeout,proto3" json:"Timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timeout) Reset()         { *m = Timeout{} }
func (m *Timeout) String() string { return proto.CompactTextString(m) }
func (*Timeout) ProtoMessage()    {}
func (*Timeout) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Timeout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timeout.Unmarshal(m, b)
}
func (m *Timeout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timeout.Marshal(b, m, deterministic)
}
func (m *Timeout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timeout.Merge(m, src)
}
func (m *Timeout) XXX_Size() int {
	return xxx_messageInfo_Timeout.Size(m)
}
func (m *Timeout) XXX_DiscardUnknown() {
	xxx_messageInfo_Timeout.DiscardUnknown(m)
}

var xxx_messageInfo_Timeout proto.InternalMessageInfo

func (m *Timeout) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

//PingMessage is for checking the connection between the Node and the server
type PingMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (m *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(m, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Profession           string   `protobuf:"bytes,3,opt,name=profession,proto3" json:"profession,omitempty"`
	Node                 string   `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetProfession() string {
	if m != nil {
		return m.Profession
	}
	return ""
}

func (m *Person) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type MultiPerson struct {
	Persons              []*Person `protobuf:"bytes,1,rep,name=Persons,json=persons,proto3" json:"Persons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MultiPerson) Reset()         { *m = MultiPerson{} }
func (m *MultiPerson) String() string { return proto.CompactTextString(m) }
func (*MultiPerson) ProtoMessage()    {}
func (*MultiPerson) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *MultiPerson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiPerson.Unmarshal(m, b)
}
func (m *MultiPerson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiPerson.Marshal(b, m, deterministic)
}
func (m *MultiPerson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiPerson.Merge(m, src)
}
func (m *MultiPerson) XXX_Size() int {
	return xxx_messageInfo_MultiPerson.Size(m)
}
func (m *MultiPerson) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiPerson.DiscardUnknown(m)
}

var xxx_messageInfo_MultiPerson proto.InternalMessageInfo

func (m *MultiPerson) GetPersons() []*Person {
	if m != nil {
		return m.Persons
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeInfo)(nil), "api.NodeInfo")
	proto.RegisterType((*NodesList)(nil), "api.NodesList")
	proto.RegisterType((*Timeout)(nil), "api.Timeout")
	proto.RegisterType((*PingMessage)(nil), "api.PingMessage")
	proto.RegisterType((*Empty)(nil), "api.Empty")
	proto.RegisterType((*Person)(nil), "api.Person")
	proto.RegisterType((*MultiPerson)(nil), "api.MultiPerson")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0x4d, 0xb2, 0x49, 0xb6, 0x39, 0x69, 0xd3, 0xf4, 0x96, 0xd6, 0x25, 0xa0, 0x94, 0x29, 0x6a,
	0x2c, 0x12, 0x6a, 0xe2, 0x07, 0xf4, 0x45, 0xfc, 0xa2, 0x14, 0xac, 0x96, 0xd5, 0x07, 0x5f, 0xb7,
	0xdd, 0x69, 0x58, 0x68, 0x76, 0x96, 0x99, 0x89, 0xe0, 0xab, 0x3f, 0xc8, 0xdf, 0x28, 0x3b, 0xbb,
	0xad, 0x33, 0x1b, 0x4d, 0xe2, 0xdb, 0xdc, 0x99, 0x7b, 0xee, 0xb9, 0xe7, 0x5c, 0xe6, 0xa2, 0x13,
	0x65, 0xc9, 0x28, 0x93, 0x42, 0x0b, 0xf2, 0xa2, 0x2c, 0x61, 0x63, 0x6c, 0x7c, 0x12, 0x31, 0x3f,
	0x4b, 0xaf, 0x05, 0xf5, 0xd0, 0x48, 0xe2, 0xa0, 0x7e, 0x50, 0x1f, 0x76, 0xc2, 0x46, 0x12, 0xd3,
	0x3e, 0xda, 0x4a, 0xcc, 0xe5, 0x15, 0x0f, 0x1a, 0xe6, 0xae, 0x8c, 0xd8, 0x31, 0x3a, 0x39, 0x46,
	0x7d, 0x4c, 0x94, 0xa6, 0x43, 0xb4, 0x4c, 0x10, 0xd4, 0x0f, 0xbc, 0x61, 0x77, 0xbc, 0x35, 0xca,
	0x09, 0x6e, 0x4b, 0x86, 0xad, 0x34, 0x7f, 0x63, 0x87, 0xf0, 0xbf, 0x26, 0x33, 0x2e, 0xe6, 0x9a,
	0x82, 0xbb, 0xa3, 0x61, 0xf2, 0x42, 0x5f, 0x17, 0x21, 0xbb, 0x8f, 0xee, 0x45, 0x92, 0x4e, 0xcf,
	0xb9, 0x52, 0xd1, 0x94, 0x57, 0xbb, 0x61, 0x3e, 0x5a, 0x1f, 0x66, 0x99, 0xfe, 0xc1, 0x2e, 0xd1,
	0xbe, 0xe0, 0x52, 0x89, 0x94, 0x08, 0xcd, 0x34, 0x9a, 0xf1, 0x32, 0xc9, 0x9c, 0xa9, 0x0f, 0x2f,
	0x9a, 0x16, 0x1d, 0x7b, 0x61, 0x7e, 0xa4, 0x07, 0x40, 0x26, 0xc5, 0x35, 0x57, 0x2a, 0x11, 0x69,
	0xe0, 0x99, 0x5c, 0xeb, 0xc6, 0x54, 0x11, 0x31, 0x0f, 0x9a, 0x65, 0x15, 0x11, 0x73, 0xf6, 0x1c,
	0xdd, 0xf3, 0xf9, 0x8d, 0x4e, 0x4a, 0xa2, 0x87, 0xf0, 0x8b, 0xd3, 0xad, 0xcc, 0xae, 0x91, 0x59,
	0xdc, 0x85, 0x7e, 0x56, 0xbc, 0x8d, 0x7f, 0xb6, 0xe0, 0xbf, 0x13, 0xa9, 0x96, 0xe2, 0x86, 0x1e,
	0x63, 0xe3, 0xbd, 0x14, 0x59, 0xee, 0x04, 0xb9, 0xa6, 0x0c, 0x60, 0xc2, 0x42, 0x4c, 0x8d, 0x9e,
	0xa0, 0x93, 0x1b, 0x69, 0x4c, 0x24, 0xeb, 0x69, 0xd0, 0xbb, 0x43, 0x19, 0xa7, 0x59, 0x8d, 0x26,
	0xd8, 0x3b, 0xe5, 0xfa, 0x73, 0xca, 0x0b, 0xe2, 0xb7, 0x52, 0x44, 0xf1, 0x55, 0xa4, 0x34, 0xd9,
	0xed, 0x0c, 0xec, 0x80, 0xd5, 0x68, 0x84, 0xbe, 0x0d, 0x32, 0x0d, 0x2d, 0xcb, 0x7f, 0x8d, 0x7b,
	0xa7, 0x5c, 0x5b, 0xea, 0xff, 0xd0, 0xf4, 0x4d, 0xa6, 0xf5, 0x34, 0x58, 0xb8, 0x61, 0x35, 0x3a,
	0x01, 0xb9, 0x05, 0x0c, 0xe5, 0x7a, 0xd8, 0x09, 0xf6, 0x73, 0xd7, 0x56, 0x49, 0x74, 0x1d, 0x1c,
	0x61, 0xc7, 0x01, 0x2d, 0x4a, 0x74, 0xf3, 0x4f, 0x10, 0xe4, 0xf9, 0x6b, 0x4a, 0x74, 0xb1, 0x2f,
	0xb0, 0x5b, 0xc1, 0xfe, 0x43, 0x9d, 0x0b, 0x3b, 0xc6, 0xee, 0x59, 0xaa, 0xb8, 0xd4, 0x6b, 0x37,
	0xf9, 0x0a, 0x7b, 0x05, 0xe2, 0x3f, 0xa9, 0xc6, 0xbf, 0x1a, 0x68, 0x7f, 0xe1, 0xf2, 0x3b, 0x97,
	0x74, 0x84, 0x4d, 0x7b, 0xf4, 0x4b, 0xc7, 0xfe, 0x12, 0x3d, 0x77, 0x6a, 0x6b, 0x4e, 0xec, 0x08,
	0x5b, 0x8e, 0xf9, 0xcb, 0x34, 0x3d, 0xc3, 0x76, 0xc5, 0xbc, 0x95, 0xc6, 0x3d, 0xc5, 0x76, 0xc5,
	0xb8, 0x65, 0x04, 0x13, 0xec, 0x2c, 0x98, 0xb6, 0xd2, 0xb0, 0x6f, 0x68, 0x1a, 0x63, 0x1f, 0xa1,
	0x99, 0xef, 0x9f, 0x32, 0xdf, 0x5a, 0x45, 0x15, 0x92, 0x21, 0xfc, 0x37, 0x71, 0xfc, 0xb7, 0x8f,
	0xbd, 0x69, 0xc2, 0x72, 0xbd, 0xb1, 0xda, 0x65, 0xdb, 0x2c, 0xda, 0xc9, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xdc, 0x06, 0x1d, 0xf4, 0x75, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlClient interface {
	DropNode(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Empty, error)
	ListNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodesList, error)
	GetOnePersonBroadcast(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error)
	GetOnePersonNode(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error)
	GetMultiPersonBroadcast(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*MultiPerson, error)
	GetMultiPersonNode(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*MultiPerson, error)
	DropOnePersonBroadcast(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Empty, error)
	DropOnePersonNode(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Empty, error)
	DropMultiPersonBroadcast(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*Empty, error)
	DropMultiPersonNode(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*Empty, error)
	InsertOnePersonNode(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Empty, error)
	InsertMultiPersonNode(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*Empty, error)
}

type controlClient struct {
	cc *grpc.ClientConn
}

func NewControlClient(cc *grpc.ClientConn) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) DropNode(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Control/DropNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) ListNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodesList, error) {
	out := new(NodesList)
	err := c.cc.Invoke(ctx, "/api.Control/ListNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) GetOnePersonBroadcast(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/api.Control/GetOnePersonBroadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) GetOnePersonNode(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/api.Control/GetOnePersonNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) GetMultiPersonBroadcast(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*MultiPerson, error) {
	out := new(MultiPerson)
	err := c.cc.Invoke(ctx, "/api.Control/GetMultiPersonBroadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) GetMultiPersonNode(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*MultiPerson, error) {
	out := new(MultiPerson)
	err := c.cc.Invoke(ctx, "/api.Control/GetMultiPersonNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) DropOnePersonBroadcast(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Control/DropOnePersonBroadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) DropOnePersonNode(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Control/DropOnePersonNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) DropMultiPersonBroadcast(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Control/DropMultiPersonBroadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) DropMultiPersonNode(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Control/DropMultiPersonNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) InsertOnePersonNode(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Control/InsertOnePersonNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) InsertMultiPersonNode(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Control/InsertMultiPersonNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServer is the server API for Control service.
type ControlServer interface {
	DropNode(context.Context, *NodeInfo) (*Empty, error)
	ListNodes(context.Context, *Empty) (*NodesList, error)
	GetOnePersonBroadcast(context.Context, *Person) (*Person, error)
	GetOnePersonNode(context.Context, *Person) (*Person, error)
	GetMultiPersonBroadcast(context.Context, *MultiPerson) (*MultiPerson, error)
	GetMultiPersonNode(context.Context, *MultiPerson) (*MultiPerson, error)
	DropOnePersonBroadcast(context.Context, *Person) (*Empty, error)
	DropOnePersonNode(context.Context, *Person) (*Empty, error)
	DropMultiPersonBroadcast(context.Context, *MultiPerson) (*Empty, error)
	DropMultiPersonNode(context.Context, *MultiPerson) (*Empty, error)
	InsertOnePersonNode(context.Context, *Person) (*Empty, error)
	InsertMultiPersonNode(context.Context, *MultiPerson) (*Empty, error)
}

func RegisterControlServer(s *grpc.Server, srv ControlServer) {
	s.RegisterService(&_Control_serviceDesc, srv)
}

func _Control_DropNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).DropNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Control/DropNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).DropNode(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Control/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).ListNodes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_GetOnePersonBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).GetOnePersonBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Control/GetOnePersonBroadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).GetOnePersonBroadcast(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_GetOnePersonNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).GetOnePersonNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Control/GetOnePersonNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).GetOnePersonNode(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_GetMultiPersonBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiPerson)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).GetMultiPersonBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Control/GetMultiPersonBroadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).GetMultiPersonBroadcast(ctx, req.(*MultiPerson))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_GetMultiPersonNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiPerson)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).GetMultiPersonNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Control/GetMultiPersonNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).GetMultiPersonNode(ctx, req.(*MultiPerson))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_DropOnePersonBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).DropOnePersonBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Control/DropOnePersonBroadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).DropOnePersonBroadcast(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_DropOnePersonNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).DropOnePersonNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Control/DropOnePersonNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).DropOnePersonNode(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_DropMultiPersonBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiPerson)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).DropMultiPersonBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Control/DropMultiPersonBroadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).DropMultiPersonBroadcast(ctx, req.(*MultiPerson))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_DropMultiPersonNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiPerson)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).DropMultiPersonNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Control/DropMultiPersonNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).DropMultiPersonNode(ctx, req.(*MultiPerson))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_InsertOnePersonNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).InsertOnePersonNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Control/InsertOnePersonNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).InsertOnePersonNode(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_InsertMultiPersonNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiPerson)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).InsertMultiPersonNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Control/InsertMultiPersonNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).InsertMultiPersonNode(ctx, req.(*MultiPerson))
	}
	return interceptor(ctx, in, info, handler)
}

var _Control_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Control",
	HandlerType: (*ControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DropNode",
			Handler:    _Control_DropNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _Control_ListNodes_Handler,
		},
		{
			MethodName: "GetOnePersonBroadcast",
			Handler:    _Control_GetOnePersonBroadcast_Handler,
		},
		{
			MethodName: "GetOnePersonNode",
			Handler:    _Control_GetOnePersonNode_Handler,
		},
		{
			MethodName: "GetMultiPersonBroadcast",
			Handler:    _Control_GetMultiPersonBroadcast_Handler,
		},
		{
			MethodName: "GetMultiPersonNode",
			Handler:    _Control_GetMultiPersonNode_Handler,
		},
		{
			MethodName: "DropOnePersonBroadcast",
			Handler:    _Control_DropOnePersonBroadcast_Handler,
		},
		{
			MethodName: "DropOnePersonNode",
			Handler:    _Control_DropOnePersonNode_Handler,
		},
		{
			MethodName: "DropMultiPersonBroadcast",
			Handler:    _Control_DropMultiPersonBroadcast_Handler,
		},
		{
			MethodName: "DropMultiPersonNode",
			Handler:    _Control_DropMultiPersonNode_Handler,
		},
		{
			MethodName: "InsertOnePersonNode",
			Handler:    _Control_InsertOnePersonNode_Handler,
		},
		{
			MethodName: "InsertMultiPersonNode",
			Handler:    _Control_InsertMultiPersonNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerClient interface {
	GetOnePerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error)
	GetMultiPerson(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*MultiPerson, error)
	DropOnePerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Empty, error)
	DropMultiPerson(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*Empty, error)
	InsertOnePerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Empty, error)
	InsertMultiPerson(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*Empty, error)
}

type serverClient struct {
	cc *grpc.ClientConn
}

func NewServerClient(cc *grpc.ClientConn) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) GetOnePerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/api.Server/GetOnePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) GetMultiPerson(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*MultiPerson, error) {
	out := new(MultiPerson)
	err := c.cc.Invoke(ctx, "/api.Server/GetMultiPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) DropOnePerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Server/DropOnePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) DropMultiPerson(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Server/DropMultiPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) InsertOnePerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Server/InsertOnePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) InsertMultiPerson(ctx context.Context, in *MultiPerson, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Server/InsertMultiPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
type ServerServer interface {
	GetOnePerson(context.Context, *Person) (*Person, error)
	GetMultiPerson(context.Context, *MultiPerson) (*MultiPerson, error)
	DropOnePerson(context.Context, *Person) (*Empty, error)
	DropMultiPerson(context.Context, *MultiPerson) (*Empty, error)
	InsertOnePerson(context.Context, *Person) (*Empty, error)
	InsertMultiPerson(context.Context, *MultiPerson) (*Empty, error)
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_GetOnePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).GetOnePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Server/GetOnePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).GetOnePerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_GetMultiPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiPerson)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).GetMultiPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Server/GetMultiPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).GetMultiPerson(ctx, req.(*MultiPerson))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_DropOnePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).DropOnePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Server/DropOnePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).DropOnePerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_DropMultiPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiPerson)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).DropMultiPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Server/DropMultiPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).DropMultiPerson(ctx, req.(*MultiPerson))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_InsertOnePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).InsertOnePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Server/InsertOnePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).InsertOnePerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_InsertMultiPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiPerson)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).InsertMultiPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Server/InsertMultiPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).InsertMultiPerson(ctx, req.(*MultiPerson))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOnePerson",
			Handler:    _Server_GetOnePerson_Handler,
		},
		{
			MethodName: "GetMultiPerson",
			Handler:    _Server_GetMultiPerson_Handler,
		},
		{
			MethodName: "DropOnePerson",
			Handler:    _Server_DropOnePerson_Handler,
		},
		{
			MethodName: "DropMultiPerson",
			Handler:    _Server_DropMultiPerson_Handler,
		},
		{
			MethodName: "InsertOnePerson",
			Handler:    _Server_InsertOnePerson_Handler,
		},
		{
			MethodName: "InsertMultiPerson",
			Handler:    _Server_InsertMultiPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*Empty, error)
	AddNode(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Timeout, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Node/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) AddNode(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Timeout, error) {
	out := new(Timeout)
	err := c.cc.Invoke(ctx, "/api.Node/AddNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	Ping(context.Context, *PingMessage) (*Empty, error)
	AddNode(context.Context, *NodeInfo) (*Timeout, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Ping(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).AddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/AddNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).AddNode(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Node_Ping_Handler,
		},
		{
			MethodName: "AddNode",
			Handler:    _Node_AddNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
